#ifndef PLANTSIZE_H
#define PLANTSIZE_H

#define PEASHOOTER_W 71
#define PEASHOOTER_H 71
#define BLOCK_W_PEASHOOTER_SPACE 8

#define SUNFLOWER_W 73
#define SUNFLOWER_H 74
#define BLOCK_W_SUNFLOWER_SPACE 8

#define WALLNUT_W 65
#define WALLNUT_H 73
#define BLOCK_W_WALLNUT_SPACE 10

#define CHERRYBOMB_W 213
#define CHERRYBOMB_H 196
#define BLOCK_W_CHERRYBOMB_SPACE -60
#define BLOCK_V_CHERRYBOMB_SPACE -60

#define TORCHWOOD_W 73
#define TORCHWOOD_H 87
#define BLOCK_W_TORCHWOOD_SPACE 8
#define BLOCK_V_TORCHWOOD_SPACE -10

#endif // PLANTSIZE_H
