#ifndef ZOMBIESIZE_H
#define ZOMBIESIZE_H

#define ZOMBIE_W 166    //zombie, coneHeadZombie, BucketHeadZombie
#define ZOMBIE_H 144
#define ZOMBIE_H_SPACE 80
#define ZOMBIE_V_SPACE 70

#define CONE_ZOMBIE_H_SPACE 95

#define BUCKET_ZOMBIE_H_SPACE 70

#define POLE_ZOMBIE_W 348
#define POLE_ZOMBIE_H 218
#define POLE_ZOMBIE_H_SPACE 200
#define POLE_ZOMBIE_V_SPACE 130

#define NEWSPAPER_ZOMBIE_W 216
#define NEWSPAPER_ZOMBIE_H 164
#define NEWSPAPER_ZOMBIE_H_SPACE 75
#define NEWSPAPER_ZOMBIE_V_SPACE 80

#endif // ZOMBIESIZE_H
